import { MinecraftBlockTypes } from '@minecraft/vanilla-data';

export const glassBlocks = [
	MinecraftBlockTypes.Glass,
	MinecraftBlockTypes.GlassPane,
	MinecraftBlockTypes.WhiteStainedGlass,
	MinecraftBlockTypes.WhiteStainedGlassPane,
	MinecraftBlockTypes.LightGrayStainedGlass,
	MinecraftBlockTypes.LightGrayStainedGlassPane,
	MinecraftBlockTypes.GrayStainedGlass,
	MinecraftBlockTypes.GrayStainedGlassPane,
	MinecraftBlockTypes.BlackStainedGlass,
	MinecraftBlockTypes.BlackStainedGlassPane,
	MinecraftBlockTypes.BrownStainedGlass,
	MinecraftBlockTypes.BrownStainedGlassPane,
	MinecraftBlockTypes.RedStainedGlass,
	MinecraftBlockTypes.RedStainedGlassPane,
	MinecraftBlockTypes.OrangeStainedGlass,
	MinecraftBlockTypes.OrangeStainedGlassPane,
	MinecraftBlockTypes.YellowStainedGlass,
	MinecraftBlockTypes.YellowStainedGlassPane,
	MinecraftBlockTypes.LimeStainedGlass,
	MinecraftBlockTypes.LimeStainedGlassPane,
	MinecraftBlockTypes.GreenStainedGlass,
	MinecraftBlockTypes.GreenStainedGlassPane,
	MinecraftBlockTypes.CyanStainedGlass,
	MinecraftBlockTypes.CyanStainedGlassPane,
	MinecraftBlockTypes.LightBlueStainedGlass,
	MinecraftBlockTypes.LightBlueStainedGlassPane,
	MinecraftBlockTypes.BlueStainedGlass,
	MinecraftBlockTypes.BlueStainedGlassPane,
	MinecraftBlockTypes.PurpleStainedGlass,
	MinecraftBlockTypes.PurpleStainedGlassPane,
	MinecraftBlockTypes.MagentaStainedGlass,
	MinecraftBlockTypes.MagentaStainedGlassPane,
	MinecraftBlockTypes.PinkStainedGlass,
	MinecraftBlockTypes.PinkStainedGlassPane,
];
